const level1 = new Level(
  [
    new JellyFish(),
    new JellyFish(),
    new JellyFish(),
    new JellyFish(),
    new JellyFish(),
    new JellyFish(),
    new Pufferfish(),
    new Pufferfish(),
    new Pufferfish(),
    new Pufferfish(),
    new Endboss(),
  ],
  [new Barrier()],
  [
    new BackgroundObjects("img/3. Background/Layers/5. Water/D.png", 0),
    new BackgroundObjects("img/3. Background/Layers/3.Fondo 1/D.png", 0),
    new BackgroundObjects("img/3. Background/Layers/4.Fondo 2/D.png", 0),
    new BackgroundObjects("img/3. Background/Layers/2. Floor/D.png", 0),
    // new BackgroundObjects("img/3. Background/Layers/1. Light/COMPLETO.png", 0),
    new BackgroundObjects("img/3. Background/Layers/5. Water/D.png", 1440),
    new BackgroundObjects("img/3. Background/Layers/3.Fondo 1/D.png", 1440),
    new BackgroundObjects("img/3. Background/Layers/4.Fondo 2/D.png", 1440),
    new BackgroundObjects("img/3. Background/Layers/2. Floor/D.png", 1440),
    new BackgroundObjects(
      "img/3. Background/Layers/1. Light/COMPLETO.png",
      1440
    ),
    new BackgroundObjects("img/3. Background/Layers/5. Water/D.png", 2880),
    new BackgroundObjects("img/3. Background/Layers/3.Fondo 1/D.png", 2880),
    new BackgroundObjects("img/3. Background/Layers/4.Fondo 2/D.png", 2880),
    new BackgroundObjects("img/3. Background/Layers/2. Floor/D.png", 2880),
  ],
  [
    new Coin(1310, 390),
    new Coin(1350, 340),
    new Coin(1400, 300),
    new Coin(1460, 280),
    new Coin(1520, 300),
    new Coin(1570, 340),
    new Coin(1610, 390),
    new Coin(900, 50),
    new Coin(950, 50),
    new Coin(1000, 50),
    new Coin(700, 300),
    new Coin(750, 300),
    new Coin(800, 300),
    new Coin(2310, 30),
    new Coin(2350, 80),
    new Coin(2400, 120),
    new Coin(2460, 130),
    new Coin(2520, 120),
    new Coin(2570, 80),
    new Coin(2610, 30),
  ],
  [
    new Poison(),
    new Poison(),
    new Poison(),
    new Poison(),
    new Poison(),
    new Poison(),
    new Poison(),
    new Poison(),
    new Poison(),
    new Poison(),
  ]
);
